# Generated by Django 6.0 on 2026-09-23 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_roleprivilege_role_alter_userprofile_role'),
        ('properties', '0009_brand_media_uploads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerHrmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrms_enabled', models.BooleanField(default=False, help_text='Admin flips this when the owner subscribes to HRMS')),
                ('industry', models.CharField(choices=[('real_estate', 'Real estate'), ('construction', 'Construction'), ('other', 'Other')], default='other', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='10-digit number; 91 is prepended for wa.me links', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a 10-digit mobile number.')])),
                ('is_paid', models.BooleanField(default=False)),
                ('subscription_ends_on', models.DateField(blank=True, null=True)),
                ('button_color', models.CharField(blank=True, default='', max_length=20)),
                ('header_color', models.CharField(blank=True, default='', max_length=20)),
                ('bg_color', models.CharField(blank=True, default='', max_length=20)),
                ('text_color', models.CharField(blank=True, default='', max_length=20)),
                ('sidebar_color', models.CharField(blank=True, default='', max_length=20)),
                ('button_style', models.CharField(blank=True, default='', max_length=40)),
                ('theme_preset', models.CharField(blank=True, default='', max_length=40)),
                ('theme_edited_at', models.CharField(blank=True, default='', help_text='YYYY-MM of last owner theme edit (one change per month)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrms_settings', to='accounts.brand')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner HRMS settings',
                'verbose_name_plural': 'Owner HRMS settings',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('site_type', models.CharField(choices=[('project', 'Project'), ('home', 'Home'), ('renovation', 'Renovation'), ('construction', 'Construction'), ('other', 'Other')], default='project', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrms_sites', to='accounts.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_sites_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_sites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_sites', to='properties.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a 10-digit mobile number.')])),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('job_role', models.CharField(blank=True, default='', max_length=80)),
                ('team', models.CharField(blank=True, default='', max_length=80)),
                ('leader', models.CharField(blank=True, default='', max_length=80)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=120)),
                ('employment_type', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('emergency', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_not_working', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrms_employees', to='accounts.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_employees_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_employee', to=settings.AUTH_USER_MODEL)),
                ('default_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrms.site')),
            ],
            options={
                'ordering': ['emp_code'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('punch_in', models.TimeField(blank=True, null=True)),
                ('punch_out', models.TimeField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('General', 'General')], default='General', max_length=20)),
                ('lat_in', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('long_in', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lat_out', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('long_out', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('project', models.CharField(blank=True, default='', max_length=120)),
                ('company_name', models.CharField(blank=True, default='', max_length=120)),
                ('overtime', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('regularized', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day'), ('Leave', 'Leave')], default='Present', max_length=20)),
                ('remark', models.TextField(blank=True, default='')),
                ('approval_status', models.CharField(choices=[('N/A', 'N/A'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='N/A', max_length=20)),
                ('punch_code_in', models.CharField(blank=True, default='', max_length=15)),
                ('punch_code_out', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrms_attendance', to='accounts.brand')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_attendance', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='hrms.employee')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='hrms.site')),
            ],
            options={
                'ordering': ['-date', 'employee__emp_code'],
            },
        ),
        migrations.CreateModel(
            name='SiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_site_assignments', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hrms.site')),
            ],
            options={
                'ordering': ['site__name', 'manager__username'],
            },
        ),
        migrations.CreateModel(
            name='SiteDailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('employees_present_count', models.PositiveIntegerField(default=0)),
                ('work_done', models.TextField(blank=True, default='')),
                ('percent_complete', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hrms_site_updates', to='accounts.brand')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_updates_posted', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_site_updates', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='hrms.site')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteMaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hrms.sitedailyupdate')),
            ],
            options={
                'verbose_name_plural': 'Site material entries',
                'ordering': ['item'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('owner', 'emp_code'), name='hrms_emp_owner_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('owner', 'mobile'), name='hrms_emp_owner_mobile_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='hrms_attendance_emp_date_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='siteassignment',
            unique_together={('site', 'manager')},
        ),
        migrations.AddConstraint(
            model_name='sitedailyupdate',
            constraint=models.UniqueConstraint(fields=('site', 'manager', 'date'), name='hrms_site_update_uniq'),
        ),
    ]
