# Generated by Django 6.0 on 2026-08-06 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50)),
                ('primary_color', models.CharField(default='#0b5fff', max_length=20)),
                ('secondary_color', models.CharField(default='#111827', max_length=20)),
                ('button_color', models.CharField(default='#0b5fff', max_length=20)),
                ('button_text_color', models.CharField(default='#ffffff', max_length=20)),
                ('background_color', models.CharField(default='#f4f6f8', max_length=20)),
                ('surface_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#111827', max_length=20)),
                ('font_style', models.CharField(choices=[('syne_source', 'Syne + Source Sans 3'), ('inter_system', 'Inter + System'), ('cinzel_josefin', 'Cinzel + Josefin Sans'), ('georgia_arial', 'Georgia + Arial'), ('mono', 'Monospace')], default='syne_source', max_length=30)),
                ('table_format', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact'), ('bordered', 'Bordered'), ('striped', 'Striped')], default='comfortable', max_length=20)),
                ('border_radius', models.CharField(choices=[('sharp', 'Sharp'), ('soft', 'Soft'), ('round', 'Round')], default='soft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site theme',
            },
        ),
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['role', 'label'],
                'unique_together': {('role', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('tenant', 'Tenant')], default='owner', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
