# Generated by Django 6.0 on 2026-08-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_brand_multibrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand context when this action happened', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this login belongs to (data is isolated per brand)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='accounts.brand'),
        ),
    ]
