# Generated by Django 6.0 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_brand_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rent_reminder_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Show a reminder when rent is due this month',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_due_day',
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text='Day of the month rent is due (1–28)',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_days_before',
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text='How many days before the due date to start reminding you',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_email_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Also send the reminder to the email on this account',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_last_sent_on',
            field=models.DateField(
                blank=True,
                help_text='Last date an email reminder was sent',
                null=True,
            ),
        ),
    ]
