# Generated by Django 6.0 on 2026-08-25 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_rent_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reminder_days_before',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many days before the due date to start reminding you', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rent_due_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of the month rent is due (1–28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
