# Generated by Django 6.0 on 2026-08-31 05:37

import accounts.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_reminder_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, help_text='Optional wide banner for marketing pages', null=True, upload_to=accounts.media_paths.brand_banner_upload),
        ),
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.ImageField(blank=True, help_text='Square icon / favicon for this brand', null=True, upload_to=accounts.media_paths.brand_icon_upload),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main brand logo shown in the app header', null=True, upload_to=accounts.media_paths.brand_logo_upload),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo for header and account screens', null=True, upload_to=accounts.media_paths.user_avatar_upload),
        ),
    ]
