# Generated by Django 6.0 on 2026-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_brand_media_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleprivilege',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('employee', 'Employee'), ('tenant', 'Tenant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('manager', 'Manager'), ('employee', 'Employee'), ('tenant', 'Tenant')], default='owner', max_length=20),
        ),
    ]
