# Generated by Django 6.0 on 2026-08-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_brand_data_isolation'),
        ('properties', '0003_property_contact_phone_tenant_advance_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='expense',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='property',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Parent brand — properties (and related rows) are isolated per brand', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='accounts.brand'),
        ),
    ]
