# Generated by Django 6.0 on 2026-08-24 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_brand_data'),
        ('properties', '0004_brand_data_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('rent', 'Rent inquiry'), ('buy', 'Buy inquiry')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='allow_tenant_marketing',
            field=models.BooleanField(default=False, help_text='Allow linked tenants to create marketing campaigns for this property'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi', 'Semi-furnished'), ('fully', 'Fully furnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For rent'), ('sale', 'For sale')], default='rent', help_text='Rent or sale — one type per property', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='possession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for sale listings', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('under_offer', 'Under offer'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for rent listings', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('magicbricks', 'MagicBricks'), ('99acres', '99acres'), ('housing', 'Housing.com'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('olx', 'OLX'), ('website', 'Website'), ('referral', 'Referral'), ('other', 'Other')], max_length=30)),
                ('listing_url', models.URLField(blank=True, default='')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('leads_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_campaigns', to='accounts.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('creator', 'Creator'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_publish', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_collaborations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='properties.marketingcampaign')),
            ],
            options={
                'ordering': ['-can_publish', 'role', 'invited_at'],
            },
        ),
        migrations.CreateModel(
            name='SitePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/%Y/%m/')),
                ('cta_label', models.CharField(blank=True, default='', max_length=80)),
                ('cta_url', models.URLField(blank=True, default='')),
                ('placement', models.CharField(choices=[('homepage', 'Homepage'), ('marketing_page', 'Marketing page'), ('both', 'Both')], default='marketing_page', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_promotions', to='accounts.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_promotions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['brand', 'status'], name='properties__brand_i_f40cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['property', 'status'], name='properties__propert_9dc7a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncollaborator',
            unique_together={('campaign', 'user')},
        ),
        migrations.AddIndex(
            model_name='sitepromotion',
            index=models.Index(fields=['brand', 'is_active', 'sort_order'], name='properties__brand_i_4f93c4_idx'),
        ),
    ]
