# Generated by Django 6.0 on 2026-08-25 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_campaign_collaborator_invite_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='content_reminder_note',
            field=models.TextField(blank=True, default='', help_text='Note included when reminding collaborators to create content for the seller'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='photos_per_day',
            field=models.PositiveIntegerField(default=0, help_text='How many photo posts collaborators should publish each day'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='videos_per_day',
            field=models.PositiveIntegerField(default=0, help_text='How many video posts collaborators should publish each day'),
        ),
        migrations.CreateModel(
            name='CampaignContentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('photos_count', models.PositiveIntegerField(default=0)),
                ('videos_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_logs', to='properties.marketingcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_content_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['campaign', 'work_date'], name='properties__campaig_6e197c_idx')],
                'unique_together': {('campaign', 'user', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='CampaignTaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='The day this reminder is about')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_messages', to='properties.marketingcampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_task_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='properties__recipie_bcdb89_idx')],
                'unique_together': {('campaign', 'recipient', 'work_date')},
            },
        ),
    ]
