# Generated by Django 6.0 on 2026-08-25 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_reminder_days_before_and_more'),
        ('properties', '0007_campaign_content_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='due', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('lease', 'Lease'), ('id_proof', 'ID proof'), ('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('invoice', 'Invoice'), ('sale_agreement', 'Sale agreement'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('visit', 'Visit'), ('offer', 'Offer'), ('note', 'Note'), ('converted', 'Converted')], default='note', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water')], default='electricity', max_length=20)),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reading_date', models.DateField()),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meters/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='sale', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('manual', 'Manual / simulated'), ('upi', 'UPI'), ('razorpay', 'Razorpay')], default='manual', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, default='', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('buyer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('token_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('token_date', models.DateField(blank=True, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('token', 'Token'), ('agreement', 'Agreement'), ('registered', 'Registered'), ('cancelled', 'Cancelled')], default='token', max_length=20)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rent_due', 'Rent due'), ('enquiry', 'Enquiry'), ('visit', 'Visit'), ('offer', 'Offer'), ('complaint', 'Complaint'), ('campaign_invite', 'Campaign invite'), ('campaign_task', 'Campaign task'), ('lease_expiry', 'Lease expiry'), ('message', 'Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=400)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('civil', 'Civil'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='properties.marketingcampaign'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='converted_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_enquiries', to='properties.tenant'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='lost_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='owner_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='preferred_move_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('campaign', 'Campaign'), ('walk_in', 'Walk-in'), ('portal', 'Portal'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visit_scheduled', 'Visit scheduled'), ('visit_done', 'Visit done'), ('offer', 'Offer'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('lost', 'Lost'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late fee charged after the grace period', max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='late_fee_grace_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Days after due date before late fee applies'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, default='', help_text='Unit / flat / room number within the building', max_length=40),
        ),
        migrations.AddField(
            model_name='propertyshare',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Agent commission % on rent or sale for this share', max_digits=5),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('landmark', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=6)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('year_of_building', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2026)])),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='buildings', to='properties.amenity')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='accounts.brand')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='properties.building'),
        ),
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Optional parent building — leave empty for a standalone listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='properties.building'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['brand', 'building'], name='properties__brand_i_702a3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('building__isnull', False), models.Q(('unit_number', ''), _negated=True)), fields=('building', 'unit_number'), name='uniq_building_unit_number'),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_payouts', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payouts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='document',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.building'),
        ),
        migrations.AddField(
            model_name='document',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_activities', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='properties.enquiry'),
        ),
        migrations.AddField(
            model_name='leadvisit',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_visits', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='leadvisit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_visits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadvisit',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.enquiry'),
        ),
        migrations.AddField(
            model_name='leadvisit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_visits', to='properties.property'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_threads', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='properties.property'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='properties.tenant'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.messagethread'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='offer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.enquiry'),
        ),
        migrations.AddField(
            model_name='offer',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='rent_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='properties.rentpayment'),
        ),
        migrations.AddField(
            model_name='saledeal',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_deals', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='saledeal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_deals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledeal',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_deals', to='properties.enquiry'),
        ),
        migrations.AddField(
            model_name='saledeal',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='properties.offer'),
        ),
        migrations.AddField(
            model_name='saledeal',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_deals', to='properties.property'),
        ),
        migrations.AddField(
            model_name='document',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.saledeal'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='converted_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_enquiries', to='properties.saledeal'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['brand', 'status'], name='properties__brand_i_d91e23_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['property', 'status'], name='properties__propert_336e6b_idx'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_listings', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='properties.property'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='accounts.brand'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['brand', 'owner'], name='properties__brand_i_288039_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['brand', 'city'], name='properties__brand_i_48618a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagethread',
            unique_together={('property', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'property')},
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read'], name='properties__user_id_e03578_idx'),
        ),
    ]
