# Generated by Django 6.0 on 2026-08-31 05:37

import accounts.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_building_crm_and_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.building_photo_upload),
        ),
        migrations.AddField(
            model_name='campaigncontentlog',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.campaign_proof_upload),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.enquiry_photo_upload),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.campaign_cover_upload),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Primary listing photo (gallery images are stored separately)', null=True, upload_to=accounts.media_paths.property_cover_upload),
        ),
        migrations.AddField(
            model_name='tenant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.tenant_photo_upload),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.complaint_photo_upload),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=accounts.media_paths.document_file_upload),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.meter_photo_upload),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=accounts.media_paths.property_gallery_upload),
        ),
        migrations.AlterField(
            model_name='sitepromotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.media_paths.promotion_image_upload),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_document',
            field=models.FileField(blank=True, null=True, upload_to=accounts.media_paths.tenant_lease_upload),
        ),
    ]
