from django.urls import path

from . import extra_views, views

urlpatterns = [
    path('', views.public_listings, name='public_listings'),
    path('listings/<int:pk>/', views.public_property_detail, name='public_detail'),
    path('listings/<int:pk>/save/', extra_views.saved_toggle, name='saved_toggle'),
    path('saved/', extra_views.saved_listings, name='saved_listings'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/rent-reminder/', views.rent_reminder_send, name='rent_reminder_send'),
    path('reports/', views.reports, name='reports'),
    path('reports.csv', extra_views.reports_csv, name='reports_csv'),
    path('tenants/', extra_views.tenant_list, name='tenant_list'),
    path('inbox/', extra_views.inbox, name='inbox'),
    path('inbox/mark-all/', extra_views.inbox_mark_all, name='inbox_mark_all'),
    path('calendar/', extra_views.calendar_view, name='calendar_view'),
    path('commissions/', extra_views.commissions, name='commissions'),
    path('buildings/', extra_views.building_list, name='building_list'),
    path('buildings/add/', extra_views.building_create, name='building_create'),
    path('buildings/<int:pk>/', extra_views.building_detail, name='building_detail'),
    path('buildings/<int:pk>/edit/', extra_views.building_edit, name='building_edit'),
    path('buildings/<int:pk>/units/add/', extra_views.building_unit_add, name='building_unit_add'),
    path('buildings/<int:pk>/units/attach/', extra_views.building_unit_attach, name='building_unit_attach'),
    path('enquiries/', views.enquiries_inbox, name='enquiries_inbox'),
    path('leads/', views.enquiries_inbox, name='leads_inbox'),
    path('leads/<int:pk>/', extra_views.lead_detail, name='lead_detail'),
    path('leads/<int:pk>/update/', extra_views.lead_update, name='lead_update'),
    path('leads/<int:pk>/visits/add/', extra_views.lead_visit_add, name='lead_visit_add'),
    path('leads/<int:pk>/offers/add/', extra_views.lead_offer_add, name='lead_offer_add'),
    path('leads/<int:pk>/convert-tenant/', extra_views.lead_convert_tenant, name='lead_convert_tenant'),
    path('leads/<int:pk>/convert-deal/', extra_views.lead_convert_deal, name='lead_convert_deal'),
    path('enquiries/<int:enquiry_id>/read/', views.enquiry_mark_read, name='enquiry_mark_read'),
    path('tenant-portal/', views.tenant_portal, name='tenant_portal'),
    path('tenant-portal/pay/<int:payment_id>/', extra_views.tenant_pay, name='tenant_pay'),
    path('my-properties/', views.my_properties, name='my_properties'),
    path('my-properties/add/', views.property_create, name='property_create'),
    path('my-properties/<int:pk>/', views.property_manage, name='property_manage'),
    path('my-properties/<int:pk>/edit/', views.property_edit, name='property_edit'),
    path('my-properties/<int:pk>/vacate/', views.property_vacate, name='property_vacate'),
    path('my-properties/<int:pk>/delete/', views.property_delete, name='property_delete'),
    path('my-properties/<int:pk>/tenants/add/', views.tenant_add, name='tenant_add'),
    path('my-properties/<int:pk>/tenants/<int:tenant_id>/edit/', views.tenant_edit, name='tenant_edit'),
    path(
        'my-properties/<int:pk>/tenants/<int:tenant_id>/login/',
        views.tenant_create_login,
        name='tenant_create_login',
    ),
    path(
        'my-properties/<int:pk>/join-requests/<int:request_id>/',
        views.join_request_review,
        name='join_request_review',
    ),
    path('my-properties/<int:pk>/payments/add/', views.payment_add, name='payment_add'),
    path('my-properties/<int:pk>/documents/add/', extra_views.document_add, name='document_add'),
    path('my-properties/<int:pk>/meters/add/', extra_views.meter_add, name='meter_add'),
    path('my-properties/<int:pk>/messages/', extra_views.thread_view, name='thread_view'),
    path('marketing/', views.marketing, name='marketing'),
    path('marketing/campaigns/add/', views.campaign_create, name='campaign_create'),
    path('marketing/campaigns/<int:pk>/', views.campaign_detail, name='campaign_detail'),
    path('marketing/campaigns/<int:pk>/edit/', views.campaign_edit, name='campaign_edit'),
    path('marketing/campaigns/<int:pk>/delete/', views.campaign_delete, name='campaign_delete'),
    path('marketing/campaigns/<int:pk>/invite/', views.campaign_invite, name='campaign_invite'),
    path('marketing/campaigns/<int:pk>/log-content/', views.campaign_log_content, name='campaign_log_content'),
    path('marketing/invites/<int:pk>/accept/', views.campaign_accept_invite, name='campaign_accept_invite'),
    path('marketing/invites/<int:pk>/decline/', views.campaign_decline_invite, name='campaign_decline_invite'),
    path(
        'marketing/task-messages/<int:pk>/read/',
        views.campaign_task_message_read,
        name='campaign_task_message_read',
    ),
    path(
        'my-properties/<int:pk>/payments/<int:payment_id>/delete/',
        views.payment_delete,
        name='payment_delete',
    ),
    path(
        'my-properties/<int:pk>/payments/<int:payment_id>/receipt/',
        views.payment_receipt,
        name='payment_receipt',
    ),
    path(
        'my-properties/<int:pk>/payments/<int:payment_id>/receipt.pdf',
        views.payment_receipt_pdf,
        name='payment_receipt_pdf',
    ),
    path('my-properties/<int:pk>/images/add/', views.image_add, name='image_add'),
    path('my-properties/<int:pk>/images/<int:image_id>/delete/', views.image_delete, name='image_delete'),
    path('my-properties/<int:pk>/expenses/add/', views.expense_add, name='expense_add'),
    path(
        'my-properties/<int:pk>/expenses/<int:expense_id>/delete/',
        views.expense_delete,
        name='expense_delete',
    ),
    path('my-properties/<int:pk>/share/', views.share_add, name='share_add'),
    path(
        'my-properties/<int:pk>/share/<int:share_id>/remove/',
        views.share_remove,
        name='share_remove',
    ),
    path(
        'my-properties/<int:pk>/complaints/<int:complaint_id>/',
        views.complaint_update,
        name='complaint_update',
    ),
]
